name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Test:
    if: ${{!contains(github.event.head_commit.message, '[skip ci]')}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v5

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Format ✨
        run: pnpm run test.format

      - name: Lint ✨
        run: pnpm run test.lint

      # - name: Tests
      #   run: |
      #     pnpm test

  # Release:
  #   needs: [Test]
  #   if: github.ref == 'refs/heads/master' &&
  #     github.event.repository.fork == false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: UziTech/action-setup-atom@v1
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "12.x"
  #     - name: NPM install
  #       run: npm install
  #     - name: Release 🎉
  #       uses: cycjimmy/semantic-release-action@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
