name: CI
on:
  - push
  - pull_request

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        atom_channel: [stable, beta]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Tests
        run: |
          pnpm test

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v5

      - name: Install dependencies
        run: npm install

      - name: Format ✨
        run: npm run test.format

      - name: Lint ✨
        run: npm run test.lint

  Release:
    needs: [Test, Lint]
    if: github.ref == 'refs/heads/master' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: UziTech/action-setup-atom@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "12.x"
      - name: NPM install
        run: npm install
      - name: Release 🎉
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
